export const USER_SIGNUP = 'USER_SIGNUP' // 注册用户
export const SAVE_QUESTIONNAIRE = 'SAVE_QUESTIONNAIRE' //保存问卷
export const PUBLISH_QUESTIONNAIRE = 'PUBLISH_QUESTIONNAIRE' //发布问卷
export const CLOSE_QUESTIONNAIRE = 'CLOSE_QUESTIONNAIRE' // 关闭问卷，状态变为已结束
export const DELETE_QUESTIONNAIRE = 'DELETE_QUESTIONNAIRE' //删除问卷
export const SUBMIT_QUESTIONNAIRE = 'SUBMIT_QUESTIONNAIRE' //提交问卷